### ISSUE TITLE
I can't see my titile that I have added 

### ISSUE THREAD

**Issue by coder-agent47** [coder-agent47/pomodoro-timer#3]

**Comment by sarthakahuja07** [comment]
Hi!! Can you assign this to me, I would love to work on this

**Comment by dhairyathedev** [comment]
Ohk! Let me see if I can help you

**Comment by coder-agent47** [comment]
@sarthakahuja07 I am giving @snowbit-coderboi chance because he had helped me before

**Comment by sarthakahuja07** [comment]
@coder-agent47 its alright , just let me know if there is another issue that I could work on

**Comment by coder-agent47** [comment]
@sarthakahuja07 how did you found this repositry?

**Comment by sarthakahuja07** [comment]
@coder-agent47 using hacktoberfest tag

**Comment by sarthakahuja07** [comment]
Is this a legit hacktoberfest repo?? @coder-agent47

**Comment by dhairyathedev** [comment]
@sarthakahuja07 I have a project running in react if you want to contribute

**Comment by sarthakahuja07** [comment]
@snowbit-coderboi sure I would love to, can you link it to me

**Comment by dhairyathedev** [comment]
@sarthakahuja07 you know react?

**Comment by sarthakahuja07** [comment]
@snowbit-coderboi yes I worked on some projects with react, you can look at my profile

**Comment by dhairyathedev** [comment]
ok

**Comment by dhairyathedev** [comment]
@sarthakahuja07 This is link to my project https://github.com/snowbit-coderboi/word-count

**Comment by dhairyathedev** [comment]
@sarthakahuja07 so what you have decided?

**Comment by sarthakahuja07** [comment]
@snowbit-coderboi check dms

**Comment by dhairyathedev** [comment]
@sarthakahuja07 where to check dms?
